version: '3.8'

services:
  # Vite React SPA served via nginx
  ekaty-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        # Map uses free Leaflet + OpenStreetMap (no API key needed)
        VITE_GOOGLE_PLACES_API_KEY: ${VITE_GOOGLE_PLACES_API_KEY}
        VITE_APP_URL: ${VITE_APP_URL}
        VITE_APP_NAME: ${VITE_APP_NAME}
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional: Backend API service (if needed)
  # api-server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - NODE_ENV=production
  #     - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
  #     - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
  #   restart: unless-stopped

networks:
  default:
    name: ekaty-network