[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Next.js output)
  publish = "out"
  
  # Note: Functions disabled for static site deployment
  # functions = "netlify/functions"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--prefer-offline --no-audit"

# Production build settings
[context.production]
  command = "npm run build"
  
# Deploy preview settings (for pull requests)
[context.deploy-preview]
  command = "npm run build"
  
# Branch deploy settings
[context.branch-deploy]
  command = "npm run build"

# Redirects for static site deployment
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  headers = {Cache-Control = "public, max-age=31536000, immutable"}

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin configuration - removed @netlify/plugin-nextjs as it's incompatible with static export
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://ekaty.com"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing",
      "yandex"
    ]